# Generated by Django 2.0 on 2018-06-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptionTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_id', models.CharField(max_length=20, verbose_name='youtube caption track id')),
                ('language', models.CharField(max_length=20, verbose_name='caption language')),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.TimeField(verbose_name='captions begin')),
                ('end', models.TimeField(verbose_name='captions end')),
                ('content', models.CharField(max_length=500, verbose_name='caption content')),
                ('captiontrack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.CaptionTrack')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20, verbose_name='youtube video id')),
                ('title', models.CharField(max_length=200, verbose_name='video title')),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.AddField(
            model_name='captiontrack',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Video'),
        ),
    ]
