# Generated by Django 2.0.6 on 2018-06-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20180619_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='captiontrack',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified time'),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified time'),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='short_title',
            field=models.CharField(default='', max_length=30, verbose_name='short version of caption content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtitle',
            name='yomi',
            field=models.CharField(default='', max_length=500, verbose_name='hiragana yomi for the content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified time'),
        ),
        migrations.AlterField(
            model_name='captiontrack',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
