# Generated by Django 2.0.6 on 2018-06-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20180621_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captiontrack',
            name='caption_id',
            field=models.CharField(max_length=50, verbose_name='youtube caption track id'),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='short_title',
            field=models.CharField(max_length=50, verbose_name='short version of caption content'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=500, verbose_name='video title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=50, verbose_name='youtube video id'),
        ),
    ]
