# Generated by Django 2.0.6 on 2018-06-24 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20180622_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='video published'),
            preserve_default=False,
        ),
    ]
