# Generated by Django 2.0.6 on 2018-07-03 05:28

from django.db import migrations, models


def make_site_settings(apps, schema_editor):
    # Like `from sirobutton import Site`
    Site = apps.get_model('sirobutton', 'Site')

    site_id = 1
    domain = 'sirobutton.herokuapp.com'
    name = 'sirobutton'
    defaluts = dict(domain=domain, name=name)
    Site.objects.update_or_create(id=site_id, defaults=defaluts)


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20180625_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='enable flag'),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='frozen',
            field=models.BooleanField(default=False, verbose_name='frozen flag'),
        ),
        migrations.RunPython(make_site_settings),
    ]
