# Generated by Django 2.0.6 on 2018-07-03 11:39

from django.db import migrations
from django.contrib.sites.models import Site


def make_site_settings(apps, schema_editor):
    # Like `from sirobutton import Site`
    site_id = 1
    domain = 'sirobutton.herokuapp.com'
    name = 'sirobutton'
    defaluts = dict(domain=domain, name=name)
    Site.objects.update_or_create(id=site_id, defaults=defaluts)


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20180703_0528'),
    ]

    operations = [
        migrations.RunPython(make_site_settings),
    ]
