# Generated by Django 2.1.3 on 2018-11-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('twitter_id', models.CharField(max_length=30, verbose_name='Twitter id')),
                ('oauth_token', models.CharField(max_length=50, verbose_name='OAuth Token')),
                ('oauth_secret', models.CharField(max_length=50, verbose_name='OAuth Secret Token')),
                ('last_prefix', models.CharField(max_length=50, verbose_name='Prefix of the name since last updated')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last modified time')),
            ],
        ),
    ]
